### ISSUE TITLE
Negative numbers and string tests

### ISSUE THREAD

**Issue by CharlesHolbrow** [CharlesHolbrow/rppp#2]
# Negative Numbers

The current rules for parsing `int`s don't handle negative numbers. Update the [initial.pegjs](https://github.com/CharlesHolbrow/rppp/blob/master/pegjs/initial.pegjs#L49) int rules to get the integer tests (`$ npm test`) to pass.

The [Pegjs JSON parser](https://github.com/pegjs/pegjs/blob/master/examples/json.pegjs) example does this if you want an example

# Strings Edge Cases

Reaper has some unusual string escaping rules. For some examples, look at the track `NAME` fields in [tricky-strings.rpp](https://github.com/CharlesHolbrow/rppp/blob/master/rpp-examples/tricky-strings.RPP-bak)

Get the [tests for the string edge cases](https://github.com/CharlesHolbrow/rppp/blob/master/tests/test.js#L67-L84) to pass by updating the [pegjs string rules in intial.js](https://github.com/CharlesHolbrow/rppp/blob/master/pegjs/initial.pegjs#L45-L46)

**Comment by zhiweigan** [comment]
Resolved in cc702d0cebc61efa43b59258711527b2c7b327e6
