### ISSUE TITLE
Lines with first parameter as decimal seem to error

### ISSUE THREAD

**Issue by JohnnyMarnell** [CharlesHolbrow/rppp#20]
Observed for at least jsfx like
```
<JS
   1.0 2
>
```
whereas this works
```
<JS
   1 2.0
>
```

PR with example tests: https://github.com/CharlesHolbrow/rppp/pull/19

Great tool!

**Comment by CharlesHolbrow** [comment]
closed by 5bf8c88e6c12f396cd469b78bda1593bcca3b5be
