### ISSUE TITLE
Add tests and then implementation for recursive objects

### ISSUE THREAD

**Issue by CharlesHolbrow** [CharlesHolbrow/rppp#3]
Right now, Objects can only contain structs, not other objects. 

Add tests for recursive objects, then implement

**Comment by zhiweigan** [comment]
I've written a test for and implemented the recursive functionality, but I would appreciate a second look before closing this issue.

**Comment by CharlesHolbrow** [comment]
@zhiweigan We talked about this on the call a bit. I think your choice to separate `header` and `lines` is very good. It seems like the my original member names could be better. What about `.contents` instead of `.lines`

**Comment by zhiweigan** [comment]
@CharlesHolbrow would it be a good idea to get rid of the ```types``` key as well and just replace it with a header?

**Comment by CharlesHolbrow** [comment]
Thinking about this a little more... object should 'look' the same as a
struct: it should have a .token and .params. unlike a struct It should also
have a .contents array.

... As if

**Comment by zhiweigan** [comment]
Implemented in 76b64f7f0d149dfffc302399dc0bb5c8f72673a1
