### ISSUE TITLE
Multiline parameters

### ISSUE THREAD

**Issue by CharlesHolbrow** [CharlesHolbrow/rppp#4]
exist in three places

1. NOTES Objects (SHould be parsed an object with a NOTES TOKEN and a single string parameter)
1. Strings that start with a string delimiter (```'`"```) and contain all delimiters ([example](https://github.com/CharlesHolbrow/rppp/blob/766a98f0a989eee17b2c24eb5f2281d9471b2e5a/rpp-examples/tricky-strings.RPP#L402-L405))
1. VSTs/Plugins containing Base64

**Comment by zhiweigan** [comment]
76b64f7f0d149dfffc302399dc0bb5c8f72673a1 Multiline parameters implemented for notes, strings that start with a string delimiter and VSTs. VSTs have not been split into three distinct chunks, this might probably be easier to do in Javascript, so I'm reading up more about the format of VST3's before continuing.
