### ISSUE TITLE
Look into simplifying specialization

### ISSUE THREAD

**Issue by CharlesHolbrow** [CharlesHolbrow/rppp#5]
If the added complexity of this section in the specializer is not necessary, it would be nice to handle the specialization of `SOUCRE` objects in the recursion.
https://github.com/CharlesHolbrow/rppp/blob/develop/src/specialize.js#L24-L37

So instead of having subclasses for `ReaperAudioItem` we would have subclasses for `ReaperAudioSource`

This will make things more maintainable in the long run.

**Comment by zhiweigan** [comment]
Made a new class, ReaperItem, which can contain ReaperAudioSources and ReaperMidiSources.

Removed addMidiItem and addAudioItem in favor of addItem which takes a generic ReaperItem.
